apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-blog
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nextjs-blog
  template:
    metadata:
      labels:
        app: nextjs-blog
    spec:
      containers:
      - name: nextjs-blog
        image: your-registry/nextjs-blog:v1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nextjs-blog-service
spec:
  selector:
    app: nextjs-blog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer